import PokemonKlassen.Pokemon
import PokemonKlassen.PokemonAttacke

enum class PokemonTyp {
    NORMAL,
    FEUER,
    WASSER,
    ELEKTRO,
    PFLANZE,
    EIS,
    KAMPF,
    GIFT,
    BODEN,
    FLUG,
    PSYCHO,
    KÄFER,
    GESTEIN,
    GEIST,
    DRACHE,
    UNLICHT,
    STAHL,
    FEE
}

val multiplikatoren = mapOf(
    PokemonTyp.NORMAL to mapOf(
        PokemonTyp.GESTEIN to 0.5,
        PokemonTyp.GEIST to 0.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.PFLANZE to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.UNLICHT to 1.0
    ),
    PokemonTyp.FEUER to mapOf(
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.WASSER to 0.5,
        PokemonTyp.PFLANZE to 2.0,
        PokemonTyp.EIS to 2.0,
        PokemonTyp.KÄFER to 2.0,
        PokemonTyp.STAHL to 2.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.DRACHE to 0.5,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.GESTEIN to 0.5
    ),
    PokemonTyp.WASSER to mapOf(
        PokemonTyp.FEUER to 2.0,
        PokemonTyp.WASSER to 0.5,
        PokemonTyp.PFLANZE to 0.5,
        PokemonTyp.ELEKTRO to 0.5,
        PokemonTyp.EIS to 0.5,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.DRACHE to 0.5,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.BODEN to 2.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.STAHL to 1.0
    ),
    PokemonTyp.ELEKTRO to mapOf(
        PokemonTyp.WASSER to 2.0,
        PokemonTyp.ELEKTRO to 0.5,
        PokemonTyp.BODEN to 0.0,
        PokemonTyp.STAHL to 1.0,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 2.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 0.5,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 0.5
    ),
    PokemonTyp.PFLANZE to mapOf(
        PokemonTyp.WASSER to 2.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 2.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 0.5,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 0.5,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 0.5,
        PokemonTyp.GIFT to 0.5,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 0.5
    ),
    PokemonTyp.EIS to mapOf(
        PokemonTyp.WASSER to 0.5,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 2.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 2.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 2.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.EIS to 0.5,
        PokemonTyp.PFLANZE to 2.0
    ),
    PokemonTyp.KAMPF to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 2.0,
        PokemonTyp.KÄFER to 0.5,
        PokemonTyp.UNLICHT to 2.0,
        PokemonTyp.FLUG to 0.5,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 0.5,
        PokemonTyp.GEIST to 0.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 0.5,
        PokemonTyp.NORMAL to 2.0,
        PokemonTyp.FEE to 0.5,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.EIS to 2.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.GIFT to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 0.5,
        PokemonTyp.STAHL to 0.0,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 0.5,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 0.5,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 2.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 0.5,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 2.0
    ),
    PokemonTyp.BODEN to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 2.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 2.0,
        PokemonTyp.KÄFER to 0.5,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 0.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 2.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 2.0,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 0.5
    ),
    PokemonTyp.FLUG to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 0.5,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 2.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 2.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 0.5,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 2.0
    ),
    PokemonTyp.PSYCHO to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 0.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 2.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 2.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.KÄFER to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 2.0,
        PokemonTyp.FLUG to 0.5,
        PokemonTyp.KAMPF to 0.5,
        PokemonTyp.PSYCHO to 2.0,
        PokemonTyp.GEIST to 0.5,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 0.5,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 0.5,
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 0.5
    ),
    PokemonTyp.GESTEIN to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 0.5,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 2.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 2.0,
        PokemonTyp.KAMPF to 0.5,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 2.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 2.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.GEIST to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 0.5,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 2.0,
        PokemonTyp.GEIST to 2.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 0.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.DRACHE to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 2.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 0.0,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 0.5
    ),
    PokemonTyp.UNLICHT to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 0.5,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 0.5,
        PokemonTyp.PSYCHO to 2.0,
        PokemonTyp.GEIST to 2.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 0.5,
        PokemonTyp.FEUER to 1.0,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.STAHL to mapOf(
        PokemonTyp.WASSER to 0.5,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 1.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 1.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 1.0,
        PokemonTyp.GIFT to 1.0,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.GESTEIN to 2.0,
        PokemonTyp.EIS to 2.0,
        PokemonTyp.PFLANZE to 1.0
    ),
    PokemonTyp.FEE to mapOf(
        PokemonTyp.WASSER to 1.0,
        PokemonTyp.ELEKTRO to 1.0,
        PokemonTyp.BODEN to 1.0,
        PokemonTyp.STAHL to 0.5,
        PokemonTyp.KÄFER to 1.0,
        PokemonTyp.UNLICHT to 2.0,
        PokemonTyp.FLUG to 1.0,
        PokemonTyp.KAMPF to 2.0,
        PokemonTyp.PSYCHO to 1.0,
        PokemonTyp.GEIST to 1.0,
        PokemonTyp.DRACHE to 2.0,
        PokemonTyp.GIFT to 0.5,
        PokemonTyp.NORMAL to 1.0,
        PokemonTyp.FEE to 1.0,
        PokemonTyp.FEUER to 0.5,
        PokemonTyp.GESTEIN to 1.0,
        PokemonTyp.EIS to 1.0,
        PokemonTyp.PFLANZE to 1.0
    )
)








